# Generated by Django 5.2.17 on 2026-09-12 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farmerprofile',
            old_name='varification_note',
            new_name='verification_note',
        ),
    ]
